name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgresql://user:password@localhost:5432/db"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 1. Instalar PNPM primero (clave)
      - name: Instalar pnpm
        uses: pnpm/action-setup@v4

      # 2. Recién después configurar Node y cachear PNPM
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      # 3. Instalar dependencias
      - name: Instalar dependencias
        run: pnpm install

      # 4. Generar Prisma Client (necesario antes del build)
      - name: Generar Prisma Client
        run: pnpm prisma:generate

      # 5. Lint
      - name: Ejecutar Lint
        run: pnpm lint

      # 6. Build
      - name: Build del proyecto
        run: pnpm build